---
   - name: describe the hosts
     debug: msg="Computer {{ ansible_hostname }} is running {{ ansible_os_family }} or equivalent"
   - name: install the apache web server
     yum:
       name: "{{ package_name }}"
       update_cache: yes
       state: latest
     when: ansible_os_family == "RedHat"  
   - name: install apache2 web server
     apt: 
       name: apache2
       update_cache: yes 
       state: started 
     when: ansible_os_family == "Debian"       
