---
   - name: start apache web server
     service:
       name: "{{ package_name }}"
       state: started
       enabled: true
   - name: start apache2 web server
     service:
       name: apache2
       state: started
       enabled: true

